namespace Shared.Network
{
    public enum SubPacketServerOpcode : ushort
    {
        None                                    = 0x0000,
        ServerError                             = 0x0002,
        ServerServiceAccountList                = 0x000C,
        ServerCharacterList                     = 0x000D,
        ServerCharacterCreate                   = 0x000E,
        ServerEnterWorld                        = 0x000F,
        ServerRealmList                         = 0x0015,
        ServerRetainerList                      = 0x0017,
        ServerNewWorld                          = 0x0066,
        ServerChat                              = 0x0067,
        ServerLogout                            = 0x0077,
        ServerContentFinderNotify               = 0x0078,
        ServerContentFinderMemberStatus         = 0x0079,
        ServerContentFinderPlayerInNeed         = 0x007F,
        ServerContentFinderDutyInfo             = 0x007A,
        ServerContentFinderRegister             = 0x00B0,
        ServerSocialInviteResponse              = 0x00B1,
        ServerSocialMessage                     = 0x00B2,
        ServerSocialInviteUpdate                = 0x00B3,
        ServerSocialList                        = 0x00B4,
        ServerMessage                           = 0x00BC,
        ServerSocialAction                      = 0x00C4,
        ServerSocialBlacklist                   = 0x00CA,
        ServerPlayerSpawn                       = 0x0110,
        ServerActorMove                         = 0x0112,
        ServerParty                             = 0x0118,
        ServerPlayerSetup                       = 0x011E,
        ServerPlayerStateFlags                  = 0x0121,
        ServerClassSetup                        = 0x0123,
        ServerActorAppearanceUpdate             = 0x0124,
        ServerItemSetup                         = 0x0139,
        ServerContainerSetup                    = 0x013A,
        ServerInventoryUpdateFinish             = 0x013B,
        ServerInventoryUpdate                   = 0x013C,
        ServerItemUpdate                        = 0x0140,
        // all 3 invoke the same client function just with different parameters
        ServerActorAction1                      = 0x0142,
        ServerActorAction2                      = 0x0143,
        ServerActorAction3                      = 0x0144,
        ServerEventSceneStart                   = 0x0154,
        /* also call the same client function as ServerEventSceneStart
        0x0155,
        0x0156,
        0x0157,
        0x0158,
        0x0159,
        0x015A,
        0x015B,*/
        ServerEventStart                        = 0x015D,
        ServerEventStop                         = 0x015E,
        ServerQuestJournalActiveList            = 0x0171,
        ServerQuestJournalCompleteList          = 0x0173,
        ServerTerritorySetup                    = 0x019A,
        ServerAchievementList                   = 0x01CB,
        ServerContentFinderList                 = 0x01CF,
        ServerUnknown01FB                       = 0x01FB,
        ServerUnknown01FD                       = 0x01FD,
        ServerTerritoryPending                  = 0x0239
    }
}
